Logos/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

from registration.forms import RegistrationFormUniqueEmail
from registration.backends.default.views import RegistrationView

from common.views import HomeView, AddUserView, AddCompetenceView, AddBusinessTypeView, AddUserTagView,\
    logout_view, LoginView, GetAccessView, UserDetailView, PersonalView

urlpatterns = patterns('',
    # Examples:
    url(r'^$', HomeView.as_view(), name='home'),
    url(r'^logout/$', logout_view, name='logout'),
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^get-access/$', GetAccessView.as_view(), name='get-access'),
    url(r'^user/add/$', AddUserView.as_view(), name='add-user'),
    url(r'^personal/$', PersonalView.as_view(), name='personal'),
    url(r'^user/(?P<username>.*)/$', UserDetailView.as_view(), name='user-detail'),
    url(r'^competence/add/$', AddCompetenceView.as_view(), name='add-competence'),
    url(r'^tag/add/$', AddUserTagView.as_view(), name='add-user-tag'),
    url(r'^btype/add/$', AddBusinessTypeView.as_view(), name='add-business-type'),
    # url(r'^Logos/', include('Logos.foo.urls')),

    url(r'^accounts/register/$', RegistrationView.as_view(), kwargs={'form_class':RegistrationFormUniqueEmail}),
    url(r'^accounts/', include('registration.backends.default.urls')),
    # Uncomment the admin/doc line below to enable admin documentation:
#    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT}),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

common/models.py
# coding: utf-8
from django.db import models
from django.contrib.auth.models import User
from django.core.files import File
from bs4 import BeautifulSoup
import requests, urllib, os

class BusinessType(models.Model):
    """
    Модель для вида бизнеса
    """
    name = models.CharField(max_length=64, verbose_name=u'Вид бизнеса', unique=True)
    slug = models.CharField(max_length=64, verbose_name=u'Slug для вида бизнеса', unique=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Вид бизнеса'
        verbose_name_plural = u'Виды бизнеса'


class Competence(models.Model):
    """
    Модель для сферы компетентности пользователя
    """
    name = models.CharField(max_length=64, verbose_name=u'Сфера компетенции', unique=True)
    slug = models.CharField(max_length=64, verbose_name=u'Slug для сферы компетенции', unique=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Сфера компетенции'
        verbose_name_plural = u'Сферы компетенции'


class UserTag(models.Model):
    """
    Модель для пользовательских тегов. Один пользователь другому может их проставить
    """
    name = models.CharField(max_length=10, verbose_name=u'Тег', unique=True)
    slug = models.CharField(max_length=20, verbose_name=u'Slug для тега', unique=True)
    author = models.ForeignKey(User, verbose_name=u'Автор тега', related_name='author_tags')
    target = models.ForeignKey(User, verbose_name=u'Кому тег был проставлен', related_name='tags', null=True)

    def __unicode__(self):
        return self.name

    class Meta:
        verbose_name = u'Пользовательский тег'
        verbose_name_plural = u'Пользовательские теги'


class UserRating(models.Model):
    """
    Модель для пользовательского рейтинга
    """
    author = models.ForeignKey(User, verbose_name=u'Автор оценки', related_name='author_rating')
    target = models.ForeignKey(User, verbose_name=u'Кому была поставлена оценка', related_name='target_rating')
    rating = models.DecimalField(decimal_places=2, max_digits=5, verbose_name=u'Рейтинг пользователя')

    def __unicode__(self):
        return u'{}: {} -> {}'.format(self.rating, self.author, self.target)

    class Meta:
        verbose_name = u'Пользовательский рейтинг'
        verbose_name_plural = u'Пользовательские рейтинги'


class UserProfile(models.Model):
    """
    Модель для профайлов пользователя
    """
    user = models.OneToOneField(User, verbose_name=u'Пользователь', related_name='profile')
    phone = models.CharField(max_length=20, verbose_name=u'Номер телефона')
    rating = models.DecimalField(decimal_places=2, max_digits=5, default=1.0, verbose_name=u'Рейтинг пользователя')
    bTypes = models.ManyToManyField(BusinessType, verbose_name=u'Вид бизнеса', related_name='profiles')
    competences = models.ManyToManyField(Competence, verbose_name=u'Сфера компетенции', related_name='profiles')
    photo = models.ImageField(upload_to='uploads/', verbose_name=u'Фото', null=True)
    vk = models.CharField(max_length=50, verbose_name=u'Ссылка на ID vk.com')

    def save(self, *args, **kwargs):
        is_new = False
        if not self.pk:
            is_new = True
        super(UserProfile, self).save(*args, **kwargs)
        if is_new and not self.photo and self.vk:
            self.updatePhotoFromVKAvatar()

    def updatePhotoFromVKAvatar(self):
        if self.vk:
            resp = requests.get(self.vk)
            soup = BeautifulSoup(resp.text)
            url = soup.select('#page_avatar a img')[0]['src']
            result = urllib.urlretrieve(url)
            self.photo.save(
                os.path.basename(url),
                File(open(result[0]))
            )

    def __unicode__(self):
        return self.user.username

    def get_name(self):
        if self.user.first_name and self.user.last_name:
            return u'{} {}'.format(self.user.first_name, self.user.last_name)
        else:
            return self.user.username

    def get_tags(self):
        tags = [u'<a href="?tags={0}">{1}</a>'.format(tag.slug, tag.name) for tag in self.user.tags.all()]
        return u','.join(tags)

    def get_btypes(self):
        btypes = [u'<a href="?btypes={0}">{1}</a>'.format(b.slug, b.name) for b in self.bTypes.all()]
        return u','.join(btypes)

    def get_competences(self):
        competences = [u'<a href="?competences={0}">{1}</a>'.format(c.slug, c.name) for c in self.competences.all()]
        return u','.join(competences)

    class Meta:
        verbose_name = u'Профиль пользователя'
        verbose_name_plural = u'Профили пользователей'

common/views.py
# coding: utf-8
import json
from django.views.generic import TemplateView, FormView, View, ListView, DetailView
from common.forms import NewUserForm, ImageForm, UpdateProfileForm, UpdateUserForm, UpdateTagsForm
from django.contrib.auth.models import User
from django.contrib.auth import logout, login, authenticate
from pytils.translit import slugify
from django.http import HttpResponse, HttpResponseRedirect
from common.models import UserProfile, Competence, BusinessType, UserTag
from django.db.models import Q
from django.template.loader import get_template
from django.template import Context
from django.core.mail import send_mail
from django.conf import settings

class LoginView(TemplateView):
    template_name='login.html'
    errors = u''

    def get_context_data(self, **kwargs):
        ctx = super(LoginView, self).get_context_data(**kwargs)
        ctx['errors'] = self.errors
        return ctx

    def post(self, request, *args, **kwargs):
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect('/')
            else:
                self.errors = u'Пользователь не активирован'
        else:
            self.errors = u'Нет пользователя в системе с такими логином и паролем'
        return self.get(request, *args, **kwargs)

def logout_view(request):
    logout(request)
    return HttpResponseRedirect('/')

# Create your views here.
class GetAccessView(TemplateView):
    template_name = 'get-access.html'
    errors = u''
    activated = False

    def get_context_data(self, **kwargs):
        ctx = super(GetAccessView, self).get_context_data(**kwargs)
        ctx['activated'] = self.activated
        ctx['errors'] = self.errors
        return ctx

    def post(self, request, *args, **kwargs):
        email = request.POST.get('email')
        if email:
            if User.objects.filter(email=email, is_active=False).count() == 0:
                self.errors = u'В базе нет неактивных пользователей с таким email'
            else:
                user = User.objects.get(email=email, is_active=False)
                user.is_active=True
                newpassword = User.objects.make_random_password()
                user.set_password(newpassword)
                user.save()
                self.activated = True
                # send_email
                plaintxt = get_template('email/get_access_email.txt')
                c = Context({'username': user.username, 'password': newpassword})
                txt = plaintxt.render(c)
                send_mail(u'Данные для входа в систему', txt, settings.DEFAULT_FROM_EMAIL, [user.email])
        else:
            self.errors = u'Введите email'
        return self.get(request, *args, **kwargs)

class HomeView(ListView):
    template_name = 'contacts.html'
    search_query = u''
    btypes = u''
    competences = u''
    tags = u''
    qd = u''
    paginate_by = 10
    model = User
    context_object_name = 'users'

    def get_queryset(self):
        self.users = User.objects.exclude(first_name__exact='', last_name__exact='')
        if self.request.GET.get('competences'):
            self.competences = self.request.GET.get('competences')
            self.users = self.users.filter(profile__competences__slug=self.competences)
        if self.request.GET.get('btypes'):
            self.btypes = self.request.GET.get('btypes')
            self.users = self.users.filter(profile__bTypes__slug=self.btypes)
        if self.request.GET.get('tags'):
            self.tags = self.request.GET.get('tags')
            self.users = self.users.filter(tags__slug=self.tags)
        if self.request.GET.get('search_query'):
            self.search_query = self.request.GET.get('search_query')
            s = self.search_query
            f = Q(tags__slug__istartswith=s)|Q(tags__name__istartswith=s)
            f |= Q(profile__bTypes__slug__istartswith=s)|Q(profile__bTypes__name__istartswith=s)
            f |= Q(profile__competences__slug__istartswith=s)|Q(profile__competences__name__istartswith=s)
            f |= Q(first_name__istartswith=s)|Q(last_name__istartswith=s)
            self.users = self.users.filter(f)
        return self.users

    def get(self, request, *args, **kwargs):
        if request.GET.get('type') == 'reset':
            return HttpResponseRedirect('/')
        else:
            self.qd = request.GET.copy()
            if 'page' in self.qd:
                del self.qd['page']
            self.qd = self.qd.urlencode()
            if self.qd: self.qd = '?'+self.qd
            return super(HomeView, self).get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(HomeView, self).get_context_data(**kwargs)
        ctx['main_active_link'] = True
        ctx['page_suffix'] = '&page=' if self.search_query or self.tags or self.btypes or self.tags else '?page='
        ctx['active_search_query'] = self.search_query
        ctx['active_tags'] = self.tags
        ctx['active_btypes'] = self.btypes
        ctx['active_competences'] = self.competences
        ctx['query_dict'] = self.qd
        ctx['tags'] = UserTag.objects.all()
        ctx['btypes'] = BusinessType.objects.all()
        ctx['competences'] = Competence.objects.all()
        return ctx

class AddCompetenceView(View):
    def post(self, request, *args, **kwargs):
        comp = request.POST.get('competence', False)
        resp = u''
        if comp:
            c = Competence.objects.create(name=comp, slug=slugify(comp))
            resp = u'[{}, {}]'.format(c.name, c.name)
        return HttpResponse(resp)

class AddBusinessTypeView(View):
    def post(self, request, *args, **kwargs):
        btype = request.POST.get('btype', False)
        resp = u''
        if btype:
            c = BusinessType.objects.create(name=btype, slug=slugify(btype))
            resp = u'[{}, {}]'.format(c.name, c.name)
        return HttpResponse(resp)

class AddUserTagView(View):
    def post(self, request, *args, **kwargs):
        tag = request.POST.get('tag', False)
        resp = u''
        if tag:
            c = UserTag.objects.create(name=tag, slug=slugify(tag), author=request.user)
            resp =  [c.pk, c.name]
        return HttpResponse(json.dumps(resp), content_type='application/json')

class AddUserView(FormView):
    template_name = 'add-contact.html'
    form_class = NewUserForm
    success_url = '/user/add/'

    def form_invalid(self, form):
        return super(AddUserView, self).form_invalid(form)

    def form_valid(self, form):
        username = u'username{}'.format(User.objects.order_by('-pk')[0].pk + 1)
        password = User.objects.make_random_password()
        first_name = form.cleaned_data['firstname']
        last_name = form.cleaned_data['lastname']
        phone = form.cleaned_data['phone']
        vk = form.cleaned_data['vk']
        new_user = User.objects.create_user(
            username=username,
            password=password,
            email=form.cleaned_data['email'],
            first_name = first_name,
            last_name = last_name
        )
        for tag_name in form.cleaned_data['tags']:
            tag = UserTag.objects.get(name=tag_name)
            tag.author=self.request.user
            tag.target = new_user
            tag.save()

        new_user_profile = UserProfile.objects.create(
            user=new_user,
            phone=phone,
            vk=vk
        )

        for name in form.cleaned_data['businesstypes']:
            btype = BusinessType.objects.get(name=name)
            new_user_profile.bTypes.add(btype)
        for name in form.cleaned_data['competences']:
            comp = Competence.objects.get(name=name)
            new_user_profile.competences.add(comp)
        new_user_profile.save()
        ctx = self.get_context_data()
        ctx['added'] = True
        return self.render_to_response(ctx)

    def get_context_data(self, **kwargs):
        ctx = super(AddUserView, self).get_context_data(**kwargs)
        ctx['add_active_link'] = True
        return ctx

class UserDetailView(DetailView):
    model = User
    template_name = 'user-detail.html'
    context_object_name = 'usr'

    def post(self, request, *args, **kwargs):
        form = UpdateTagsForm(request.POST, instance=self.get_object())
        if form.is_valid():
            form.save()
        return self.get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        ctx = super(UserDetailView, self).get_context_data(**kwargs)
        ctx['tagsForm'] = UpdateTagsForm(instance=self.get_object())
        return ctx

    def get_object(self, queryset=None):
        return User.objects.get(username=self.kwargs['username'])

class PersonalView(TemplateView):
    template_name = 'personal.html'
    message = u''

    def post(self, request, *args, **kwargs):
        if request.POST.get('send_password'):
            newpassword = User.objects.make_random_password()
            request.user.set_password(newpassword)
            request.user.save()
            plaintxt = get_template('email/get_access_email.txt')
            c = Context({'username': request.user.username, 'password': newpassword})
            txt = plaintxt.render(c)
            self.message = u'Пароль отправлен'
            send_mail(u'Данные для входа в систему', txt, settings.DEFAULT_FROM_EMAIL, [request.user.email])
        else:
            userForm = UpdateUserForm(request.POST, request.FILES, instance=request.user)
            if userForm.is_valid():
                userForm.save()
            profileForm = UpdateProfileForm(request.POST, request.FILES, instance=request.user.profile)
            if profileForm.is_valid():
                profileForm.save()
                self.message = u'Данные сохранены'

common/templates/add-contact.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
    <div class="container">
        <form method="POST" role="form" class="form-add" enctype="multipart/form-data">{% csrf_token %}
            <div class="panel panel-default ">
                <div class="panel-heading">Добавить нового участника сети {{ form.non_field_errors }}</div>
                <div class="panel-body">
                    {% if added %}
                        <div class="alert alert-success text-center">
                            Новый участник добавлен
                        </div>
                    {% endif %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label_tag }}
                            {% if field.errors %}
                                <div class="alert alert-danger">
                                {{ field.errors }}
                                </div>
                            {% endif %}
                            {% if field.label == form.photo.label %}
                                {{ field }}
                            {% else %}
                                {% render_field field class+="form-control" %}
                            {% endif %}
                        </div>
                    {% endfor %}

                    {% if form %}
                        <button class="btn btn-lg btn-primary btn-block" type="submit">Добавить</button>
                    {% endif %}
                </div>
            </div>
        </form>
    </div>
{% endblock %}

common/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>Logos - база контактов предпринимателей</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Bootstrap -->
    <link href="{{ STATIC_URL }}css/bootstrap.min.css" rel="stylesheet">

    <link href="{{ STATIC_URL }}selectize/css/selectize.bootstrap3.css" rel="stylesheet">

    <link href="{{ STATIC_URL }}css/style.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
    <![endif]-->
</head>
<body>
<nav class="navbar navbar-default" role="navigation">
    <div class="navbar-header">
        <a class="navbar-brand">Logos</a>
    </div>
    <ul class="nav navbar-nav">
        {% if request.user.is_authenticated %}
            <li {% if main_active_link %} class="active" {% endif %}><a href="/">Список контактов</a></li>
            <li {% if add_active_link %} class="active" {% endif %}><a href="{% url 'add-user' %}">Добавить контакт</a></li>
        {% endif %}
    </ul>
    <ul class="nav navbar-nav navbar-right" style="margin-right: 0px;">
        {% if request.user.is_authenticated %}
            <li><a href="{% url 'personal' %}">
                {% if request.user.last_name and request.user.first_name %}
                    {{ request.user.last_name }} {{ request.user.first_name }}
                {% else %}
                    {{ request.user.username }}
                {% endif %}
            </a></li>
            <li>
                <a href="/logout/" title="Выйти"><span class="glyphicon glyphicon-remove"></span></a>
            </li>
        {% else %}
            <li><a href="{% url 'login' %}">Войти</a></li>
        {% endif %}
    </ul>
</nav>
{% block content %}{% endblock %}
<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://code.jquery.com/jquery.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
<script src="{{ STATIC_URL }}selectize/js/standalone/selectize.js"></script>
<script src="{{ STATIC_URL }}js/jquery.cookie.js"></script>

<script src="{{ STATIC_URL }}/js/custom.js"></script>
{% block extra_scripts %}{% endblock %}
</body>
</html>

common/templates/contacts.html
{% extends 'base.html' %}

{% block extra_scripts %}
    <script type="text/javascript">
    $(function()
    {
        $("select").selectize();
    })
    </script>
{% endblock %}

{% block content %}
    <div class="container">
    {% if request.user.is_authenticated %}
        <h3>Поиск</h3>
        <form method="GET">
            <div class="row">
                <div class="col-md-10">
                    <input value="{{ active_search_query }}" type="text" name="search_query" class="form-control" placeholder="Введите ключевое слово">
                </div>
                <div class="col-md-1">
                    <button type="submit" class="btn btn-primary btn-block" name="type" value="search">Найти</button>
                </div>
                <div class="col-md-1">
                    <button type="submit" class="btn btn-default btn-block" value="reset" name="type">Сброс</button>
                </div>
            </div>

            <div class="row" style="margin-top: 20px;">
                <div class="col-md-4">
                    <select name="tags">
                        <option value="">Выберите теги...</option>
                        {% for tag in tags %}
                            <option {% if active_tags == tag.slug %} selected="selected"{% endif %} value="{{ tag.slug }}">{{ tag.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-4">
                    <select name="btypes">
                        <option value="">Выберите виды бизнеса...</option>
                        {% for bt in btypes %}
                            <option {% if active_btypes == bt.slug %} selected="selected"{% endif %}
                                    value="{{ bt.slug }}">{{ bt.name }}</option>
                        {% endfor %}
                    </select>
                </div>
                <div class="col-md-4">
                    <select name="competences">
                        <option value="">Выберите сферы компетенции...</option>
                        {% for c in competences %}
                            <option {% if active_competences == c.slug %} selected="selected"{% endif %}
                                    value="{{ c.slug }}">{{ c.name }}</option>
                        {% endfor %}
                    </select>
                </div>
            </div>
        </form>

        <hr />

        <h3>Список контактов</h3>
        {% for item in users %}
            <div class="panel panel-default">
                <div class="panel-heading">
                    <a href="{% url 'user-detail' username=item.username %}">
                        {{ item.profile.get_name }}
                    </a>
                </div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-md-2">
                            {% if item.profile.photo %}
                                <a href="#" class="">
                                    <img src="{{ MEDIA_URL }}{{ item.profile.photo }}" class="img-thumbnail" />
                                </a>
                            {% else %}
                                <img src="{{ STATIC_URL }}img/user-detail.png" class="img-thumbnail"/>
                            {% endif %}
                        </div>
                        <div class="col-md-10">
                            Теги: {{ item.profile.get_tags|safe }}
                            <hr />
                            Сферы компетенции: {{ item.profile.get_competences|safe }}
                            <hr />
                            Виды бизнеса: {{ item.profile.get_btypes|safe }}
                        </div>
                    </div>
                </div>
            </div>
        {% empty %}
            <p>Нет подходящих записей</p>
        {% endfor %}
        {% if is_paginated %}
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li><a href="{{ query_dict }}{{ page_suffix }}{{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% endif %}
                {% for page in page_obj.paginator.page_range %}
                    <li {% if page == page_obj.number %}class="active"{% endif %}>
                        <a href="{{ query_dict }}{{ page_suffix }}{{ page }}">{{ page }}</a></li>
                {% endfor %}
                {% if page_obj.has_next %}
                    <li><a href="{{ query_dict }}{{ page_suffix }}{{ page_obj.next_page_number }}">&raquo;</a></li>
                {% endif %}
            </ul>
        {% endif %}
    {% else %}
        <div class="jumbotron">
            <h1>Logos</h1>
            <p>Система контактов начинающих предпринимателей. Предназначена для поиска поставщиков, партнеров, клиентов
                и исполнителей.</p>
        </div>
    {% endif %}
    </div>
{% endblock %}

common/templates/get-access.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <h1>Активировать пользователя</h1>
        <p>Если ваш контакт уже есть в базе, вы можете получить доступ к нему.
        Для этого введите ваш email в поле ниже и нажмите "Получить пароль".
        После этого на ваш email будут высланы логин и пароль для входа в систему.</p>
        <form method="POST" action="/get-access/" class="form-get-access">{% csrf_token %}
        {% if activated %}
            <div class="alert alert-success">
                На ваш email высланы логин и пароль для входа в систему
            </div>
        {% else %}
            <div class="panel panel-default">
                <div class="panel-heading">Введите ваш email</div>
                <div class="panel-body">
                    {% if errors %}
                        <div class="alert alert-danger">
                            {{ errors }}
                        </div>
                    {% endif %}
                        <div class="form-group">
                            <input class="form-control" name="email" />
                        </div>
                        <button type="submit" class="btn btn-block btn-primary">Получить пароль</button>
                </div>
            </div>
        {% endif %}
        </form>
    </div>
{% endblock %}

common/templates/home.html
{% extends 'base.html' %}

common/templates/personal.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block extra_scripts %}
    <script type="text/javascript">
        $(function()
        {
            $('select#id_bTypes').selectize({
                plugins: ['remove_button'],
                create: function(input) {
                    $.ajax({
                        url: '/btypes/add/',
                        type: 'POST',
                        data: {'competence': input, 'csrfmiddlewaretoken':$.cookie('csrftoken')},
                    });
                    return {
                        value: input,
                        text: input
                    }
                }
            });
        });
    </script>
{% endblock %}

{% block content %}
    <div class="container">
        <h1>Личный кабинет пользователя {{ request.user.profile.get_name }}</h1>
        <div class="panel panel-default">
            <div class="panel-body">
                <form method="POST" action="{% url 'personal' %}" enctype="multipart/form-data">{% csrf_token %}
                    <div class="row">
                        <div class="col-md-4">
                            {% if request.user.profile.photo %}
                                <img src="{{ MEDIA_URL }}{{ request.user.profile.photo }}" class="img-thumbnail" />
                            {% endif %}
                            <div class="form-group">
                                <label>Фото</label>
                                <input type="file" name="photo" />
                            </div>
                        </div>
                        <div class="col-md-8">
                            {% if message %}
                                <div class="alert alert-success">{{ message }}</div>
                            {% endif %}
                            <div class="form-group">
                                {{ userForm.last_name.label_tag }}
                                {% render_field userForm.last_name class+="form-control" %}
                            </div>
                            <div class="form-group">
                                {{ userForm.first_name.label_tag }}
                                {% render_field userForm.first_name class+="form-control" %}
                            </div>
                            <div class="form-group">
                                {{ updateForm.phone.label_tag }}
                                {% render_field updateForm.phone class+="form-control" %}
                            </div>
                            <div class="form-group">
                                {{ updateForm.vk.label_tag }}
                                {% render_field updateForm.vk class+="form-control" %}
                            </div>
                            <div class="form-group">
                                {{ updateForm.tags.label_tag }}
                                {{ updateForm.tags }}
                            </div>
                            <div class="form-group">
                                {{ updateForm.competences.label_tag }}
                                {{ updateForm.competences }}
                            </div>
                            <div class="form-group">
                                {{ updateForm.bTypes.label_tag }}
                                {{ updateForm.bTypes }}
                            </div>
                            <div class="form-group">
                                {{ userForm.tags.label_tag }}
                                {{ userForm.tags }}
                            </div>
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                            <button type="submit" name="send_password" value="yes" class="btn btn-info">Отправить на почту новый пароль</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}